/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface AppProfile {}
  interface AppRoot {}
  interface MmBadge {
    'value': string;
  }
  interface MmBricks {}
  interface MmHeader {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMmBadgeElement extends Components.MmBadge, HTMLStencilElement {}
  var HTMLMmBadgeElement: {
    prototype: HTMLMmBadgeElement;
    new (): HTMLMmBadgeElement;
  };

  interface HTMLMmBricksElement extends Components.MmBricks, HTMLStencilElement {}
  var HTMLMmBricksElement: {
    prototype: HTMLMmBricksElement;
    new (): HTMLMmBricksElement;
  };

  interface HTMLMmHeaderElement extends Components.MmHeader, HTMLStencilElement {}
  var HTMLMmHeaderElement: {
    prototype: HTMLMmHeaderElement;
    new (): HTMLMmHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'mm-badge': HTMLMmBadgeElement;
    'mm-bricks': HTMLMmBricksElement;
    'mm-header': HTMLMmHeaderElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppProfile {}
  interface AppRoot {}
  interface MmBadge {
    'value'?: string;
  }
  interface MmBricks {}
  interface MmHeader {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'mm-badge': MmBadge;
    'mm-bricks': MmBricks;
    'mm-header': MmHeader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'mm-badge': LocalJSX.MmBadge & JSXBase.HTMLAttributes<HTMLMmBadgeElement>;
      'mm-bricks': LocalJSX.MmBricks & JSXBase.HTMLAttributes<HTMLMmBricksElement>;
      'mm-header': LocalJSX.MmHeader & JSXBase.HTMLAttributes<HTMLMmHeaderElement>;
    }
  }
}


